# Generated by Django 2.2.6 on 2019-10-22 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('bboard', '0001_initial'), ('bboard', '0002_auto_20191008_2233'), ('bboard', '0003_auto_20191014_1355')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='Title')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Rubric',
                'verbose_name_plural': 'Rubrics',
            },
        ),
        migrations.CreateModel(
            name='Bb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Goods')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Describe')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Price')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='PublishedDate')),
                ('rubric', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bboard.Rubric', verbose_name='Rubric')),
            ],
            options={
                'ordering': ['-published'],
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publication',
            },
        ),
    ]
